import React, { useState } from 'react';
import { IncidentCase } from '../types';

interface CopilotModalProps {
  incident: IncidentCase;
  isOpen: boolean;
  onClose: () => void;
  onAuthorize: (incidentId: string, updatedText: string) => void;
}

export const CopilotModal: React.FC<CopilotModalProps> = ({
  incident,
  isOpen,
  onClose,
  onAuthorize,
}) => {
  const draft = incident.copilotDraft;
  const [draftContent, setDraftContent] = useState(draft?.fullText || '');
  const [recipient, setRecipient] = useState(draft?.targetRecipient || 'Elena Rostova (VP Eng, Finova)');
  const [isSending, setIsSending] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);

  if (!isOpen || !draft) return null;

  const handleSend = () => {
    setIsSending(true);
    setTimeout(() => {
      setIsSending(false);
      setIsSuccess(true);
      setTimeout(() => {
        onAuthorize(incident.id, draftContent);
        setIsSuccess(false);
        onClose();
      }, 1000);
    }, 1200);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-fadeIn">
      <div className="relative w-full max-w-lg rounded-xl bg-[#1c2027] border border-[#3c4a42] p-5 shadow-[0_20px_50px_rgba(0,0,0,0.9),inset_0_1px_1px_rgba(255,255,255,0.1)] flex flex-col gap-4 text-[#e0e2ed]">
        {/* Header */}
        <div className="flex items-center justify-between pb-3 border-b border-[#272a32]">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-full bg-[#00b2d0]/20 flex items-center justify-center shadow-[0_0_8px_#00b2d0]">
              <span className="material-symbols-outlined text-[16px] text-[#4cd7f6]">
                smart_toy
              </span>
            </div>
            <div>
              <div className="flex items-center gap-1.5">
                <span className="font-['JetBrains_Mono'] text-[11px] font-semibold text-[#4cd7f6] uppercase tracking-wider">
                  AUTONOMOUS COPILOT DISPATCH
                </span>
                <span className="w-1.5 h-1.5 rounded-full bg-[#4cd7f6] animate-pulse"></span>
              </div>
              <span className="font-['Hanken_Grotesk'] text-[13px] text-[#bbcabf]">
                Incident {incident.caseNumber} • {incident.account}
              </span>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-7 h-7 rounded-lg bg-[#272a32] text-[#bbcabf] hover:text-white flex items-center justify-center hover:bg-[#32353d] transition-colors"
          >
            <span className="material-symbols-outlined text-[18px]">close</span>
          </button>
        </div>

        {/* Dispatch Metadata Strip */}
        <div className="grid grid-cols-2 gap-2 p-2.5 rounded-lg bg-[#0b0e15] border border-[#272a32]">
          <div>
            <span className="font-['JetBrains_Mono'] text-[9px] uppercase tracking-wider text-[#86948a] block">
              TARGET RECIPIENT
            </span>
            <input
              type="text"
              value={recipient}
              onChange={(e) => setRecipient(e.target.value)}
              className="w-full bg-transparent font-['Hanken_Grotesk'] text-[13px] text-[#e0e2ed] font-medium border-b border-[#3c4a42] focus:border-[#4edea3] focus:outline-none pt-0.5"
            />
          </div>
          <div>
            <span className="font-['JetBrains_Mono'] text-[9px] uppercase tracking-wider text-[#86948a] block">
              SLA CREDIT FORECAST
            </span>
            <span className="font-['JetBrains_Mono'] text-[13px] text-[#ffb77d] font-bold">
              {draft.slaCreditEstimate} (Contractual Memo)
            </span>
          </div>
        </div>

        {/* Editable Message Box */}
        <div className="flex flex-col gap-1.5">
          <label className="font-['JetBrains_Mono'] text-[10px] uppercase tracking-wider text-[#bbcabf] flex items-center justify-between">
            <span>DISPATCH TELEGRAM BODY</span>
            <span className="text-[#86948a]">Auto-generated by Claude/Radar</span>
          </label>
          <textarea
            value={draftContent}
            onChange={(e) => setDraftContent(e.target.value)}
            rows={8}
            className="w-full rounded-lg bg-[#0b0e15] border border-[#272a32] p-3 font-['JetBrains_Mono'] text-[11px] leading-relaxed text-[#e0e2ed] focus:outline-none focus:border-[#4cd7f6] resize-none shadow-[inset_0_2px_4px_rgba(0,0,0,0.8)]"
          />
        </div>

        {/* Status / Success notice */}
        {isSuccess && (
          <div className="p-2.5 rounded-lg bg-[#003824] border border-[#4edea3]/40 flex items-center gap-2 text-[#4edea3] text-[12px] font-['JetBrains_Mono']">
            <span className="material-symbols-outlined text-[16px]">check_circle</span>
            <span>DISPATCH TRANSMITTED TO SALESFORCE &amp; CLIENT SLACK CHANNEL</span>
          </div>
        )}

        {/* Physical Action Buttons */}
        <div className="grid grid-cols-2 gap-3 pt-2">
          <button
            onClick={onClose}
            className="h-10 px-3 rounded-lg bg-[#272a32] text-[#bbcabf] hover:text-white font-['JetBrains_Mono'] text-[11px] uppercase tracking-wider shadow-[0_2px_4px_rgba(0,0,0,0.5)] active:translate-y-0.5 transition-all"
          >
            Cancel / Hold
          </button>
          <button
            onClick={handleSend}
            disabled={isSending || isSuccess}
            className="h-10 px-3 rounded-lg bg-gradient-to-r from-[#10b981] to-[#00b2d0] text-[#002113] hover:brightness-110 font-['JetBrains_Mono'] text-[11px] font-bold uppercase tracking-wider shadow-[0_4px_12px_rgba(16,185,129,0.3)] active:translate-y-0.5 transition-all flex items-center justify-center gap-1.5 disabled:opacity-50"
          >
            {isSending ? (
              <>
                <span className="w-3.5 h-3.5 border-2 border-[#002113] border-t-transparent rounded-full animate-spin"></span>
                <span>SIGNING &amp; DISPATCHING...</span>
              </>
            ) : isSuccess ? (
              <>
                <span className="material-symbols-outlined text-[16px]">done_all</span>
                <span>DISPATCHED</span>
              </>
            ) : (
              <>
                <span className="material-symbols-outlined text-[16px]">send</span>
                <span>AUTHORIZE &amp; DISPATCH</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};
